name: game100
recipe: lamp
config:
    webroot: ./public
    database: mariadb
    php: 7.2
services:
    phpmyadmin:
        type: phpmyadmin:5.0
    node:
        type: node
tooling:
    npm:
        service: node
